theme:          iiifc-theme
permalink:      pretty
root_url:       'https://preview.iiif.io/root/wireframe'
api_url:        'https://preview.iiif.io/api/wireframe/api'
guides_url:     'https://preview.iiif.io/guides/wireframe'
cookbook_url:   ''

plugins:
  - jekyll-data
  - jekyll-gzip
  - jekyll-redirect-from
  - jekyll-liquify

highlighter: none

webrick:
  headers:
    Access-Control-Allow-Origin: "*"

exclude: ["scripts", "Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]

defaults:
  -
    scope:
      path: ""
    values:
      layout: "recipe"
      livesite: "https://iiif.io"

# notification:
#   enabled: true
#   title: This website design is in pre-beta.
#   subtitle: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
#   link: '#'
#   link_label: This is a test link
